package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.dotnetPublish
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.dotnetRestore
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        dotnetRestore {
            projects = "oc-dotnetcore.csproj"
        }
        dotnetPublish {
            projects = "oc-dotnetcore.csproj"
        }
    }
    steps {
        insert(2) {
            script {
                name = "echo"
                scriptContent = """echo "Hello World""""
            }
        }
    }
}
