package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'BuildC2'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("BuildC2")
    name = "BuildC2"
    description = "2nd build config"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        script {
            name = "step1"
            scriptContent = """echo "hello world build step""""
        }
    }
}))

